version: '3'

services:
  redis:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - 6379:6379
  backend:
    image: 'ghcr.io/aleksamcode/pnls-backend-ghcr:latest'
    build:
      context: ./sniffer/
      dockerfile: ./Dockerfile
    ports: 
      - 3001:3001
  frontend:
    image: 'ghcr.io/aleksamcode/pnls-frontend-ghcr:latest'
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
