version: '3'

services:
  redis:
    image: redis:alpine
    command: redis-server
    container_name: pnls_redis
    network_mode: host
  backend:
    image: ghcr.io/aleksamcode/pnls-backend-ghcr:latest
    container_name: pnls_asgi
    build:
      context: ./sniffer/
      dockerfile: ./Dockerfile
    network_mode: host
  frontend:
    image: ghcr.io/aleksamcode/pnls-frontend-ghcr:latest
    container_name: pnls_web
    build:
      context: ./web/
      dockerfile: ./Dockerfile
    network_mode: host
